version: '3.8'
services:
  softether-vpn:
    build:
      context: ./
      dockerfile: dockerfile-softether
    container_name: softether-vpn
    environment:
      TZ: Asia/Tokyo
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - '5555:5555/tcp'
      - '500:500/udp'
      - '4500:4500/udp'
    volumes:
      # configファイル
      - ./conf/vpn_server.config:/usr/vpnserver/vpn_server.config
    environment:
      - USERS=azx213:Azx2001978!
      - PSK=azx213
      - SPW=Azx2001978!
volumes:
  softether-vpn:
    driver: local
