name: docker-rpi-softether
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t my-docker-image .

    - name: Run PHP version test
      run: docker run my-docker-image ./vpncmd /help | grep Version
